### ISSUE TITLE
[REFACTOR] 탭바 애니메이션 관련 버그 수정 및 기타 버그 수정

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#100]
## 🛠 Issue

탭바 애니메이셔 관련 버그를 수정합니다.
다른 사람 프로필 영상 재생 버그를 수정합니다.

## 📝 To-do

- [x] 탭바 애니메이셔 관련 버그 수정
- [x] 다른 사람 프로필 영상 재생 버그를 수정
- [x] 컨텐츠 리스트 bottom padding 수정
- [x] 플레이어 탭 시 일시정지/재생 구현
- [x] player pause 시 out of index 버그 개선
- [x] main 탭 NavigationStack 이 쌓인채로 다른 탭 이동 후 재진입시 플레이어가 재생되는 문제 해결
- [x] 다른 사람 컨텐츠 dismiss 시 제대로 pause 되도록 수정
