### ISSUE TITLE
[REFACTOR] 기타 버그 수정 & QA

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#113]
## 🛠 Issue

본인 프로필을 다른사람 프로필 화면에서 진입 시 팔로우 버튼 비활성화
프로필 로드 이전에는 팔로우 버튼 비활성화
앱 완전 종료 후 유니버설 링크로 컨텐츠 접속 시 컨텐츠가 중복 재생되는 문제 해결

## 📝 To-do

- [x] 본인 프로필을 다른사람 프로필 화면에서 진입 시 팔로우 버튼 비활성화
- [x] 프로필 로드 이전에는 팔로우 버튼 비활성화
- [x] 앱 완전 종료 후 유니버설 링크로 컨텐츠 접속 시 컨텐츠가 중복 재생되는 문제 해결
- [x] 팔로우 버튼 디자인 수정
