### ISSUE TITLE
[REFACTOR] QA 사항 수정

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#128]
## 🛠 Issue

QA 사항 수정

## 📝 To-do

- [x] 비로그인시 영상 3개만 보이도록 수정
- [x] 비로그인 시 홈탭 클릭시 poptoroot 해제
- [x] 비로그인 시 온보딩뷰 영상 멈춤 수정
