### ISSUE TITLE
[REFACTOR] QA 수정사항 반영 (15, 32 + 𝛂

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#139]
## 🛠 Issue

AccessView 권한 문구 수정
컨텐츠가 없는 유저의 경우 신고 플로우 변경
중복 신고 알림 .alert 방식으로 변경 (추후 API 확인 후 다시 테스트 필요)
업로드 탭 닫을 시 이전 탭 화면으로 이동 (QA 32)
타이머 뷰 해제 기능 추가 (QA 15)

## 📝 To-do

- [x] AccessView 권한 문구 수정
- [x] 컨텐츠가 없는 유저의 경우 신고 플로우 변경
- [x] 업로드 탭 닫을 시 이전 탭 화면으로 이동 (QA 32)
- [x] 타이머 뷰 해제 기능 추가 (QA 15)
