### ISSUE TITLE
[FEAT] QA 21, 22, 23

### ISSUE THREAD

**Issue by psangwon62** [WhistleGlobal/whistle-iOS#145]
## 🛠 Issue

- 음악 삽입에 대한 QA를 처리합니다.

## 📝 To-do

- [ ] 음악 리스트 클릭 시 액션
- [ ] 음악 삽입 시 음량 조절
- [ ] 음악 변경 시 음악 재생
