### ISSUE TITLE
[FEAT] 유저 차단 기능, 네비게이션 제스처

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#161]
## 🛠 Issue

유저 차단 기능, 네비게이션 제스처
메인 컨텐츠 새로고침
메인 컨텐츠 블러

## 📝 To-do

- [x] 유저 차단 기능
- [ ] 네비게이션 제스처
- [x] 메인 컨텐츠 새로고침
- [ ] 메인 컨텐츠 블러
