### ISSUE TITLE
[REFACTOR] 깨지는 뷰 수정

### ISSUE THREAD

**Issue by psangwon62** [WhistleGlobal/whistle-iOS#173]
## 🛠 Issue

깨지는 뷰를 수정합니다.

## 📝 To-do

- [x] 프로필 뷰에서 비디오의 위아래가 잘려 보이는 현상을 해결합니다.
- [x] 관심없음을 선택한 비디오의 블러가 제대로 안 되는 현상을 해결합니다.
- [x] 프로필 뷰에서 휘슬과 팔로우 사이의 선 높이를 줄입니다.
