### ISSUE TITLE
[REFACTOR] 카메라 기능 수정

### ISSUE THREAD

**Issue by psangwon62** [WhistleGlobal/whistle-iOS#177]
## 🛠 Issue

카메라 기능에 대한 오류 수정을 합니다.

## 📝 To-do

- [X] 전면 카메라 선택 시 앱이 죽는 문제
- [X] 카메라 줌인
- [X] 카메라 초점 맞추기
- [X] 촬영 UI 피그마와 동기화
