### ISSUE TITLE
[QA] 플레이어 재생 문제 및 기타 QA

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#239]
## 📝 To-do

- [x] 플레이어 재생에 관련한 버그 수정
- [x] 차단해제 스크롤 오류 수정
- [x] API 호출횟수 관련 수정
- [x] 콘텐츠가 없습니다 문구 수정
- [x] 신고 이유 순서 수정
