### ISSUE TITLE
[FEAT] 해시태그 검색 결과 추가, API 변경사항 받을 수 있도록 수정, 마이팀 선택 뷰 추가

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#245]
## 🛠 Issue

해시태그 검색 결과 추가, API 변경사항 받을 수 있도록 수정, 마이팀 선택 뷰 추가

## 📝 To-do

- [x] 해시태그 검색 결과 추가
- [x] API 변경사항 받을 수 있도록 수정
- [x] 마이팀 선택 뷰 추가
