### ISSUE TITLE
[FIX] 검색 버그, 프로필 텍스트, 랭킹 뷰 색상 수정

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#263]
## 🛠 Issue

검색 검색기록에 이미 있던 단어는 검색이 안되던 문제 수정
프로필 유저네임 텍스트 위치 수정
랭킹 뷰 색상 수정

## 📝 To-do

- [x] 검색 검색기록에 이미 있던 단어는 검색이 안되던 문제 수정
- [x] 프로필 유저네임 텍스트 위치 수정
- [x] 랭킹 뷰 색상 수정
