### ISSUE TITLE
[FEAT] 메인피드 관련 버그 수정

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#292]
## 🛠 Issue

메인 피드에서 화면 이동 후 다시 돌아올 시 마이팀 탭으로 돌아가게 되는 버그를 수정합니다.
LaunchScreen에 마이팀 피드 로드 조건을 추가합니다.

## 📝 To-do

- [x] 메인 피드에서 화면 이동 후 다시 돌아올 시 마이팀 탭으로 돌아가게 되는 버그를 수정합니다.
- [x] LaunchScreen에 마이팀 피드 로드 조건을 추가합니다.
- [x] 최근 검색어가 제대로 저장되지 않던 버그를 수정합니다.
- [x] 비로그인 시 프로필에서 poptoroot가 되던 버그를 수정합니다.
- [x] 모두 시청했습니다. 토스트로 임시 구현
- [x]  비율 안맞는 영상 블러 썸네일 처리
- [x] 휘슬 아이콘 수정
