### ISSUE TITLE
[FEAT] 메인화면 제스처, 버튼 클릭 추가

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#48]
## 🛠 Issue

메인화면 제스처를 추가합니다.

## 📝 To-do

- [ ] 오른쪽 -> 왼쪽 드래그 프로필로이동
- [ ] 휘슬 더미 더미 기능 (2초 후 상태 서버 전송)
- [ ] 더블 클릭 휘슬
- [ ] 탭바 숨기기 기능
