### ISSUE TITLE
[REFACTOR] 기타 기능 개선(최적화) 및 디자인 요소 수정

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#54]
## 📝 To-do

- [x] 아이콘 크기 수정
- [x] 커스텀 갤러리 최적화 작업
- [x] 사진 권한이 없을 시 설정 이동 처리
- [x] glassmorphism 디자인 적용 및 컴포넌트화
- [x] 프로필 사진 crop 기능 추가
