### ISSUE TITLE
[FEAT] 동영상 편집 기능 구현

### ISSUE THREAD

**Issue by psangwon62** [WhistleGlobal/whistle-iOS#58]
## 🛠 Issue

- 동영상 편집 관련 기능과 UI를 구현합니다.

## 📝 To-do

- [x] 동영상 편집 UI 구현
  - [x] 동영상 프레임 나열 UI
  - [x] 동영상 속도 조절 UI
  - [x] 동영상 음량 조절 UI
  - [x] 동영상 음악 선택 UI
- [x] 동영상 편집 기능 구현
  - [x] 동영상 프레임 나열 기능
  - [ ] 프레임 핀치 기능
  - [ ] 속도 조절 기능
  - [x] 음량 조절 기능
  - [x] 자르기 기능
  - [x] 코덱 변경 기능
  - [ ] 화질 열화 기능(?)
