### ISSUE TITLE
[FEAT] 타인 신고 게시물 신고 화면 구현, 로그아웃 기능 추가, 가입된 날짜 기능 추가

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#60]
## 📝 To-do

- [x] 타인 신고 게시물 신고 화면 구현
- [x] 가입된 날짜 기능 추가
- [x] 로그아웃 기능 추가
- [x] 구글 로그인 추가
- [x] 메인화면 비디오 현재 비디오만 로드하도록 수정
