### ISSUE TITLE
[FEAT] API 확정 후 기능 추가

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#66]
## 🛠 Issue

저장하기, 관심없음, 신고 기능 추가하기
휘슬(좋아요) 기능 추가하기 
신고받은 나의 게시물 보기 
계정삭제
탭바 애니메이션 추가하기
백스와이프 동작 네비게이션 제대로 동작하도록 수정

## 📝 To-do

- [x] 탭바 애니메이션 추가하기
- [x] 다른 사람 프로필 기존 신고 플로우 수정
- [x] 계정 삭제
신고받은 나의 게시물 보기
- [x] 휘슬 기능 추가하기
- [x] 저장하기, 관심없음, 신고기능 추가하기
- [x] 메인뷰 팔로우 추가
