### ISSUE TITLE
[FEAT] 음악 편집 구현

### ISSUE THREAD

**Issue by psangwon62** [WhistleGlobal/whistle-iOS#7]
## 🛠 Issue
음악을 편집하는 기능과 화면을 구현합니다.

## 📝 To-do

- [x] 음악 편집 기능
- [x] 음악 편집 화면
- [x] 음악 선택 화면
