### ISSUE TITLE
[REFACTOR] 메인뷰 탭이동시 플레이어 일시정지, 팔로우 뷰 -> 다른 사람 프로필 첫 진입 연결 버그

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#70]
## 🛠 Issue

메인뷰 탭이동시 플레이어 일시정지

## 📝 To-do

- [x] 메인뷰 탭이동시 플레이어 일시정지
- [x] 팔로우 뷰 -> 다른 사람 프로필 첫 진입 연결 버그
- [x] 프로필 백그라운드 이미지 변경
