### ISSUE TITLE
[FIX] 머지하면서 생긴 빌드 오류 수정

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#76]
## 🛠 Issue

머지하면서 생긴 빌드 오류 수정

confilct시 지워지지 못한 변수 삭제
TestView 삭제
package.resolved 파일 업데이트
로그인 화면 개인정보 처리방침 화면 이동 처리 & 폰트 수정

## 📝 To-do

- [x] confilct시 지워지지 못한 변수 삭제
- [x] TestView 삭제
- [x] package.resolved 파일 업데이트
- [x] 로그인 화면 개인정보 처리방침 화면 이동 처리 & 폰트 수정
