### ISSUE TITLE
[REFACTOR] 메인화면 비디오가 전부 로드되기전에도 동작하도록 수정, 다른사람 프로필 버그 수정

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#82]
## 🛠 Issue

메인화면 비디오가 전부 로드되기전에도 동작하도록 수정

## 📝 To-do

- [x] 메인화면 비디오가 전부 로드되기전에도 동작하도록 수정
- [x] 다른 사람 프로필 비디오 로드가 비정상적인 것 수정
- [x] 팔로워 뷰 이동시 팔로워 목록이 제대로 저장되도록 수정  
- [x] 프로필 컨텐츠 리스트 뒤로가기 시 플레이어가 멈추지 않는 버그 수정 
- [x] Navigation depth 관련 버그 수정
