### ISSUE TITLE
[FEAT] 잔버그 QA

### ISSUE THREAD

**Issue by dayjack** [WhistleGlobal/whistle-iOS#91]
## 🛠 Issue

잔버그 QA

## 📝 To-do

- [x] NavigationStack Pop to root 기능
- [x] Main -> 다른 사람 프로필 이동 player 재생 정지 수정
- [x] Main -> 다른 사람 프로필 이동 후 upload 탭 이동시 불투명 되는 현상 수정
- [x] 영상 관심없음 로직 수정
